//
//  GlassesReadiness.swift
//  thing-finder
//
//  Mirrors the SDK's connection state into one value the capture-source
//  switch can read.
//
//  Deliberately app code rather than an edit to ExtentosBootstrap: the
//  bootstrap is tool-managed and regenerated by generateConnectionModule, so
//  anything hand-written there is lost on the next scaffold run.
//

import Combine
import GlassesCore
import SwiftUI

@MainActor
final class GlassesReadiness: ObservableObject {
  static let shared = GlassesReadiness()

  /// True when a device is connected and usable as a camera source.
  ///
  /// One value derived from one `GlassesState`, so the capture source cannot
  /// observe a combination the connection never actually reaches. Only
  /// `Disconnected` means the link is gone — while the camera warms up the
  /// state stays `Active`.
  @Published private(set) var isReady: Bool = false

  private var task: Task<Void, Never>?

  private init() {
    let glasses = ExtentosBootstrap.shared.glasses
    task = Task { [weak self] in
      for await state in glasses.connection.state.stream {
        guard let self else { return }
        let ready = state.active != nil
        await MainActor.run { self.isReady = ready }
      }
    }
  }

  deinit {
    task?.cancel()
  }
}
